manifest: 'manifest.csv'
relation: 'relation.csv'

ascp_bin: '/data/home/dohoon/.aspera/connect/bin/ascp'
ascp_key: '/data/home/dohoon/.aspera/connect/etc/asperaweb_id_dsa.openssh'

reference:
    name: 'hg38'
    dir: '/data/project/dohoon/reference/hg38'
    fasta: '/data/project/dohoon/reference/hg38/hg38.fa'

data_dir: 'data'
result_dir: 'result'
bwa_index_dir: '/data/project/dohoon/reference/hg38/bwa_index'

threads:
    parallel_fastq_dump: 6
    trim_galore: 6
    bwa_index: 1
    bwa: 8

parallel_fastq_dump:
    extra: '--tmpdir .'

trim_galore:
    extra: ''
    quality: 20
    phred33: True
    phred64: False
    fastqc: False
    fastqc_args: False
    adapter: False
    adapter2: False
    illumina: False
    nextera: False
    small_rna: False
    max_length: False
    stringency: 1
    e: 0.1
    length: 20
    max_n: False
    trim_n: False
    no_report_file: False
    suppress_warn: False
    clip_R1: False
    clip_R2: False
    three_prime_clip_R1: False
    three_prime_clip_R2: False
    nextseq: False
    basename: False
    rrbs: False
    non_directional: False
    keep: False
    trim1: False
    retain_unpaired: False
    length_1: False
    length_2: False

bwa_index:
    extra: ''
    a: 'bwtsw'
    b: False
    _6: False

bwa_mem:
    extra: ''
    k: 19
    w: 100
    d: 100
    r: 1.5
    y: 20
    c: 500
    D: 0.50
    W: 0
    m: 50
    S: False
    P: False
    A: 1
    B: 4
    O: '6,6'
    E: '1,1'
    L: '5,5'
    U: 17
    x: False
    R: '"@RG\tID:{run}\tSM:{run}\tPL:ILLUMINA"'
    H: False
    j: False
    _5: False
    q: False
    K: False
    v: 3
    T: 30
    h: '5,200'
    a: False
    C: False
    V: False
    Y: False
    M: False
    I: False

macs2_filterdup:
    extra: ''
    gsize: 'hs'
    tsize: False
    pvalue: '1e-5'
    keep_dup: 1
    verbose: 2

macs2_callpeak_narrow:
    extra: ''
    gsize: 'hs'
    keep_dup: 1
    buffer_size: 100000
    name: False
    bdg: True
    trackline: False
    SPMR: False
    tsize: False
    bw: 300
    mfold: '5 50'
    fix_bimodal: False
    nomodel: False
    shift: 0
    extsize: 200
    pvalue: False
    qvalue: 0.05
    to_large: False
    ratio: False
    down_sample: False
    seed: 0
    tempdir: '.'
    nolambda: False
    slocal: 1000
    llocal: 10000
    broad: False
    broad_cutoff: 0.1
    cutoff_analysis: False
    call_summits: False
    fe_cutoff: 1.0

macs2_callpeak_broad:
    extra: ''
    gsize: 'hs'
    keep_dup: 1
    buffer_size: 100000
    name: False
    bdg: True
    trackline: False
    SPMR: False
    tsize: False
    bw: 300
    mfold: '5 50'
    fix_bimodal: False
    nomodel: False
    shift: 0
    extsize: 200
    pvalue: False
    qvalue: 0.05
    to_large: False
    ratio: False
    down_sample: False
    seed: 0
    tempdir: '.'
    nolambda: False
    slocal: 1000
    llocal: 10000
    broad: True
    broad_cutoff: 0.1
    cutoff_analysis: False
    call_summits: False
    fe_cutoff: 1.0

macs2_bdgcmp:
    extra: ''
    scaling_factor: 1.0
    pseudocount: False
